### ISSUE TITLE
Issue in parsing JSON object

### ISSUE THREAD

**Issue by vaibhavvats85** [consultantjay/LTIMEARN#1]
In my mongoDB collection I'm having a field i.e. array of objects which consists of symbols not allowing me to parse that field as json object

Actual:
{"product_specification"=>[{"key"=>"Number of Contents in Sales Package", "value"=>"Pack of 3"}, {"key"=>"Fabric", "value"=>"Cotton Lycra"}]}

I want to access 2 element of this array like product_specification[2]

Expected:
{"product_specification":[{"key":"Number of Contents in Sales Package", "value":"Pack of 3"}, {"key":"Fabric", "value":"Cotton Lycra"}]}

**Comment by rahulxyz** [comment]
In order to access elements, the data must be in **JSON format**. You need to replace `=>` with `:` in your **Actual data**. Mongo has a provision of **scripting in mongo shell** itself.  Try the below code 
```
var cursor= db.collectionName.find();
var doc,sel;
while(cursor.hasNext()){
	doc=cursor.next();
	fieldVar=doc.fieldName;
	print(fieldVar);
	fieldVar=fieldVar.replace(/=>/g,":");
	print(fieldVar)
}
```
In the above code, we are using cursor to iterate through each document of collection. We fetch the field in a variable and replace the character. `/g` stands for global otherwise the function will only replace first character encountered.
