### ISSUE TITLE
Issue in removing special characters from a value

### ISSUE THREAD

**Issue by arnsshef** [consultantjay/LTIMEARN#2]
My dataset involves a field named 'Price' which contains the following type of value: 
   'Price': "$150,000"  //string

I want to remove '$' and ',' from the 'Price' field for all documents(records in the dataset) and then covert it into type 'number'. 

  'Price':150000    //number

I am not authorized to use MS Excel due to security issues.
Is there any way to solve this problem?

**Comment by rahulxyz** [comment]
I'm assuming that your data is in JSON format. You can use the below code for making the above changes.
```
var cursor= db.collectionName.find();
var doc,fieldVar;
while(cursor.hasNext()){
	doc=cursor.next();
	fieldVar=doc.fieldName;
	print(fieldVar);
	fieldVar=fieldVar.replace(/$/g,"");
	fieldVar= fieldVar.replace(/,/g,"");
	var num= parseInt(fieldVar)
	print(fieldVar) // or update your document
}
```
In the above code, we are using cursor to iterate through each document of collection. We fetch the field in a variable and replace the character. /g stands for global otherwise the function will only replace first character encountered.
